Metrics/MethodLength:
  Exclude:
    - "**/*.rb"

Metrics/BlockLength:
  Exclude:
    - "**/*.rb"

Style/CommentedKeyword:
  Exclude:
    - "**/*.rb"

Style/MultilineBlockChain:
  Exclude:
    - "**/*.rb"
